name: ServerlistMOTD
author: Strumswell
version: X-2020-05-14
description: Change your Serverlist Motd!
load: POSTWORLD
depend: [ProtocolLib]
softdepend: [Vault, BanManager, MaxBans]
loadbefore: [Vault]
main: cloud.bolte.serverlistmotd.Main
commands:
   serverlist:
     description: Show list of commands
     aliases: [sl, smotd]
     permission: serverlist
     permission-message: §e§oServerlist§6§lMOTD §7> §cYou don't have permissions!
     usage: §e§oServerlist§6§lMOTD §7> §cWrong syntax! See /serverlist
permissions:
   serverlist.*:
     description: Gives access to all commands
     children:
       serverlist: true
       serverlist.reload: true
       serverlist.restrictedmode: true
       serverlist.versiontext: true
       serverlist.banmotd: true
       serverlist.whitelistmotd: true
       serverlist.randommotd: true
